# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  ui:
    image: ui
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
