FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /src
COPY ["ui.csproj", "./"]
RUN dotnet restore "ui.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "ui.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ui.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ui.dll"]
